### ISSUE TITLE
ffmpeg and avconv

### ISSUE THREAD

**Issue by odevauchelle** [hchauvet/beampy#2]
ffmpeg doesn't exist in Debian Jessie. Use avconv instead.

Install avconv:
apt-get install libav-tools 

Use it in beampy:
document._external_cmd['ffmpeg'] = 'avconv'

**Comment by hchauvet** [comment]
We should add a function to test that when we load document class, or maybe we should switch to avconv (a fork of ffmpeg). I'm not completely clear on the story of that fork...

**Comment by hchauvet** [comment]
This issue is now fixed in commit: hchauvet/beampy@689b503714165a9b732b0f94055b099a0d20429d

I add link_external_tools()  method in to document class. This function uses the parameters defined in the theme file as a dictionary in THEME['document']['external_app'].  By default the method automatically search for *ffmpeg* or *avconv* executable
